### ISSUE TITLE
Datavyu 1.5.0-RC5  - Video Controller - Andrea

### ISSUE THREAD

**Issue by TheoWolf** [databrary/datavyu_qa#4]
#### Add Data
Test to make sure Datavyu is able to load videos in all supported plugins. You may use the FrameCounter videos to test different resolutions/formats.

1. Open new instance of Datavyu.
2. On the Controller window, click Add Data.
   - [x] __Success:__ File chooser window opens up above other windows. The starting folder is the folder containing the last video added to the Controller if there are any, otherwise the user's home folder. The window contains a plugin selection drop-down menu at the bottom of the screen that defaults to FFMPEG. Video files in the current directory are selectable.
3. Choose video file to open.
   - [x] __Success:__ a new video player window opens up. The player window displays the first frame of video, or the frame at the current needle position if the needle is not at the start of the track.
4. Test adding multiple videos (using the same plugin) to the same Controller window.
   - [ ] __Success:__ Each file added creates a new track in the Controller window and a new video player window. **Check to make sure the tracks area of the Controller window is properly populated with each stream**.
5. Test resizing video windows.
   - [x] __Success:__ Video windows change size without distortion or cropping. Areas of the player window without the video frame is padded black.

Note: If there are multiple Video Plugins, repeat steps from 2 to 5 with each plugin. Windows has only the FFMPEG plugin.

#### Playback functions
Test the following playback functions using the appropriate hotkeys or Video Controller buttons.
1. Play
   - [x] Controller state moves to 1x forward playback, regardless of current speed/state.
   - [x] Playback is smooth without visible jittering or jumping. Ensure this is the case for long durations of continuous playback (e.g., 30s, 60s).
   - [ ] Compare to playback in a media player (e.g., QuickTime, VLC) if comparison is needed.
1. Shuttle forward/backward
   - [x] Shuttle forward moves playback speed to the next forward playback increment (See [Playback speeds table](https://github.com/databrary/datavyu_qa/wiki/Resources/_edit#playback-speeds)).
   - [x] Shuttle backward moves playback speed to the next backward playback increment (See [Playback speeds table](https://github.com/databrary/datavyu_qa/wiki/Resources/_edit#playback-speeds)).
   - [x] Smooth playback is expected for playback up to 2x speed.
   - [x] Playback at speeds faster than 2x should function as required but the quality of the playback may degrade. However,frames should continually update—there should be no “hanging” on a particular frame.
   - [x] Smooth playback consists of steady frame updates, no jitter,and no visible frame jumping.

   **Notes:**
    - Backward Playback with FFmpeg plugin shows stuttering from [-1/32..-4] speeds, this behavior is acceptable for a backward playback.
    - Playback increments are powers of 2 for exponents [-5..5]. There are negative as well as positive increments. Shuttle backwards from zero moves to -1/32x speed (See [Playback speeds table](https://github.com/databrary/datavyu_qa/wiki/Resources/_edit#playback-speeds)).

1. Stop
   - [x] Controller moves to 0x playback speed.
   - [x] All videos stop playing.
   - [ ] No jump in videos before the stop* (this may be broken).
   - [x] Play again and confirm that the Video Controller State is correct (Go through the checklist again).
1. Pause
   - [x] Playback stops immediately.
   - [x] Controller state should display previous playback speed with brackets surrounding it.
   - [x] Pressing Pause again resumes playback at the previous speed and removes brackets from the playback speed display.
   - [ ] No visible jumps in the video when pausing/resuming.
   - [x] Repeat steps with different playback speeds (No need to go through every playback speed one positive and one negative shuould be enough)
1. Jog forward/backward
   - [x] Open counter.mp4 video (Download the resource from [here](https://github.com/databrary/datavyu_qa/wiki/Resources/_edit#videos)).
   - [x] Jog forward advances the Controller clock forward to the next multiple of the step increment size (See Note).
   - [x] The counter video advances by one frame.
   - [x] Jog backward moves the Controller clock backward to the previous multiple of step increment (See Note).
   - [x] The counter videos step back by one frame.

   **Note:** A step increment is: ceil(1000/FPS)
1. Jump back
   - [x] Video jumps backwards by the amount indicated in the “Jump back by” field.
   - [x] Controller time updates to reflect the jump.

#### Tracks
The right side of the Controller window is the area for the video tracks. A horizontal section should be added each time a new data file is added (a track for each video stream). The left side of each track displays an icon for the plugin used to load the video. Beneath the icon are several function buttons: Lock, View, Volume, Resize, Close.
- [ ] Lock - Prevent the track from moving (via mouse drag) when enabled
- [x] View - Toggles visibility of the video window for this stream
- [x] Volume - Vertical slider to adjust the volume for this stream
- [ ] Resize - Fixed value sizes to which to scale this stream’s window
-  Close - Remove the video from the Controller
  - [ ] __Success:__ The track is removed from the Controller and other tracks (if any) are shifted to take up its space. The player window closes and leaves no traces behind.
- [ ] Stop the player and move the track after the playback needle: the player seeks and displays the first frame.
- [x] Play and wait until the needle reaches the beginning of the track.
- [ ] Move the track before the needle: the player should seek and display the last frame.
- [x] Stop the player, move the needle just before the end of the track (e.g. 5 seconds) and play: the player should stop at the last frame when the needle passes the track.
- [x] Reset the track to its original position and put the playhead needle somewhere in the middle of the track.
- [x] Set a region around the needle by moving the two green bars at the sides of the video tracks area.
- [x] Play forward and backward at different speeds: the player should pause at the boundary of a region (See Pause section for the state of the Video Controller).
- [x] When the needle is at a boundary (a green bar) move the latter: the Video Controller should stay at Paused State.

**Note:** The blue rectangle denoting a track can be dragged (if the Lock is disabled) to change the stream’s start and end position relative to the Controller clock.

#### Zoom Slider
The horizontal slider on the top-right area of the Controller window scales the granularity of the tracks display.
- [x] Zooming out all the way should show all tracks, beginning to end.
- [x] Zooming in should scale the tick marks at the bottom edge of the tracks area.
- [x] Playing while zoomed in should move the needle past the appropriate section.

#### Playhead Needle
The vertical red line in the Controller window’s track area designates the location of the current time in the video tracks.
- [x] Ensure that dragging the Needle (by right-clicking and dragging the red triangle attached to the top of the Needle) updates the clock and the video windows properly. During playback, the Needle updates and moves along the tracks area.

#### Notes
- If Datavyu is not installed on your machine, please follow [Installation Instructions](https://github.com/databrary/datavyu_qa/wiki#installation)

**Comment by ars17psu** [comment]
Notes:

- I had to install datavyu v1.5.0. The pop up window regarding data collection has a link to a webpage (http://datavyu.org/download/data-collection-policy.html) which gives an error (Not Found
The requested URL /download/data-collection-policy.html was not found on this server.)

Add Data 
- Step 4: failed when I tried to add a video that was from a network drive and datavyu closed completely. So I moved it to the desktop and started over. Everything worked fine, but the second video opened at full screen.

Every video added except for one of my videos opened at full screen. I don't know if this has to do with the resolution of the device that recorded it. Even the counter video opened at full screen.

- Step 4: When I added 3 videos, there is a scroll bar at the right side of the Data Viewer Controller to scroll through the tracks. It may be nice if the Data Viewer Controller window could be resized if more than two videos are being viewed.

I thought the video track that was clicked on and turned green would be the video in front.  It seems I need to click the video to put it in front. How do you select which video is in front?

As a result I can't tell which video goes with the stream in the video controller except by its name.

- Step 5: the mouse disappears when I am over top of the video window except for the bar at the top. The sizing is slow to respond.

Stop

- There is a slight jump when 'Stop' or 'Pause' are selected

Tracks

Lock and Resize did not work

Upon close, the window and track closed, but there was not shifting of video windows on the screen.

I have 4 tracks open. I was able to close one using the Close function button. When I closed the second then third one, datavyu froze then crashed.

**Comment by TheoWolf** [comment]
@ars17psu Thank you for your feedback, I'm mostly concerned about times when Datavyu stopped or crashed in Add Data and when closing tracks. It would be great if you can share your log file, look here C:\Users\USERACCOUNT\AppData\Local\datavyu\app\all.txt
* Indeed the link is not working will fix it ASAP.
* Datavyu will open the video with its original resolution but you still can resize if needed. 
* Datavyu should be able to open videos from a network drive, @sh0sh1n and @jperricone could you please test it in the lab and confirm it.
* Hiding the mouse on the top of an FFmpeg Window is the normal behavior but will fix it in the 1.5.1 release.
* The Jump when Stopping or Pausing is normal.
* Couldn't reproduce the crash when having multiple videos open, this has to do with releasing the player resources. the log file might help to reproduce the bug.

**Comment by ars17psu** [comment]
[all.log](https://github.com/databrary/datavyu_qa/files/3453032/all.log)

**Comment by TheoWolf** [comment]
Fixed missing link http://datavyu.org/download/data-collection-policy.html
